# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.IntegerField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.chat')),
            ],
        ),
        migrations.CreateModel(
            name='first_category',
            fields=[
                ('fcid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.address')),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('num', models.IntegerField()),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='second_category',
            fields=[
                ('scid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.first_category')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=11)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='second_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.second_category'),
        ),
        migrations.AddField(
            model_name='order_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.user'),
        ),
        migrations.AddField(
            model_name='chat_pro',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.product'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.user'),
        ),
    ]
